name: EEEEserverplugin
version: ${project.version}
main: org.wangxyper.EEEserverPlugin.Main
authors: [ wangxyper ]
description: 这是某位沙雕腐竹给他自己的沙雕服务器写的插件(bug)
commands:
 reloadeeee:
   description: 重载插件
   usage: /reloadeeee